package com.rulezero.playerconnector.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Availability {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long availabilityId;

    @Column(nullable = false, length = 64)
    private String dayOfWeek;

    @Column(nullable = false, length = 64)
    private String startTime;

    @Column(nullable = false, length = 64)
    private String endTime;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private Users user;

    // Constructors, getters, and setters will be generated by Lombok
}

