package com.rulezero.playerconnector.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Entity
@Data
public class Availability {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long availabilityId;

    @Column(nullable = false, length = 64)
    private String dayOfWeek;

    @Column(nullable = false, length = 64)
    private String startTime;

    @Column(nullable = false, length = 64)
    private String endTime;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private Users user;

    // Constructors, getters, and setters will be generated by Lombok
}

